### ISSUE TITLE
2.11 API style

### ISSUE THREAD

**Issue by johnsbrew** [freechipsproject/www.chisel-lang.org#40]
Looks like we rollback in term of style and responsiveness on https://www.chisel-lang.org/api/latest/index.html

I know we are doing hardware (which is usually associated with ugly UIs and poor UX) but I think we should not reinforce clichés.

Just checked chisel outreach meeting notes and found:
> Old documentation uses default Scala version for that project, resulting in 2.11-style documentation for a lot of projects
>

But I do not understand why we can't force documentation to be generated as of 2.12?
Is there also any good reason to have scala 2.11 as default Scala version?

**Comment by seldridge** [comment]
> I know we are doing hardware (which is usually associated with ugly UIs and poor UX) but I think we should not reinforce clichés.

:fire::fire::fire::fire::fire_engine:

> But I do not understand why we can't force documentation to be generated as of 2.12?

The problem that I ran into was the following: the website needs to build documentation for all tags that we specify. In effect, this means looping over all project--tag tuples and running `sbt doc` or `sbt unidoc`. I can globally force a Scala version with something like `sbt ++2.12.6 doc`, but there's no golden Scala version that will work across all projects.

It's easier to just do `sbt doc` and use whatever the default version of the project is. [For Chisel 3.1.8 the default Scala version is 2.11.12](https://github.com/freechipsproject/chisel3/blob/v3.1.8/build.sbt#L40). Hence, building documentation in this way results in projects that specify a default Scala version of 2.11.x building "old style" 2.11 Scaladoc while projects building with a default version of 2.12.y (e.g., [FIRRTL 1.1.7](https://github.com/freechipsproject/firrtl/blob/v1.1.7/build.sbt#L19)) will get "new style" Scaladoc.

However, I do think that this is relatively accurate in that the documentation reflects the default Scala version for *that version* of the project. [E.g., Scaladoc for Scala 2.11.12 is presented with "old style" documentation as opposed to "new style."](https://www.scala-lang.org/api/2.11.12/#package)

This specific change was applied in #30.

> Is there also any good reason to have scala 2.11 as default Scala version?

Not really anymore and this isn't the default version going forward for projects.

There are two solutions here:

1) Once 3.2 becomes "latest" then pretty new-style Scaladoc will be back
2) We manually encode each 2.12.y version when building the documentation

(2) is a mess because the documentation is [built using a Makefile](https://github.com/freechipsproject/www.chisel-lang.org/blob/master/Makefile) (I'm sorry...) and `sbt` won't allow you to just specify, e.g., `sbt +2.12 doc`.

**Comment by johnsbrew** [comment]
>     1. Once 3.2 becomes "latest" then pretty new-style Scaladoc will be back

That's perfectly fine! 👍 

Thank you for your detailed answer and the huge work with the new website 😀
