### ISSUE TITLE
FAQ.html has broken link to https://www.chisel-lang.org/chisel3/Unconnected-Wires

### ISSUE THREAD

**Issue by rpadler** [freechipsproject/www.chisel-lang.org#60]
Looks like the .html is missing from the link, thus resulting in a 404 error

**Comment by seldridge** [comment]
Hi @rpadler. Thanks for reporting this!

I think it's actually the _case sensitivity_ of the link. https://www.chisel-lang.org/chisel3/unconnected-wires should work with or without a trailing `.html` while https://www.chisel-lang.org/chisel3/Unconnected-Wires fails either way.

This should be fixed by #61 once that is merged and churns through CI.

If you encounter other errors, have high level feedback, or want to propose website PRs... it's all appreciated. :+1:
